name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -G "Unix Makefiles"
    - name: make
      working-directory: build
      run: make -j
    - name: test
      working-directory: build
      run: ctest --output-on-failure
