name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        build: [Debug, Release]
    steps:
    - name: info
      run: |
        g++ --version
        ruby --version
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build }}
    - name: make
      working-directory: build
      run: make -j
    - name: test
      working-directory: build
      run: ctest --output-on-failure
